version: '3.2'
services:
    mysql-server:
        container_name: mysql
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: secret
        image: mysql/mysql-server
        command: 
            --general-log=ON
            --log-output=TABLE
        volumes:
            - ./init:/docker-entrypoint-initdb.d
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "20080:80"
        environment:
            WORDPRESS_DB_HOST: mysql-server:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: secret
        depends_on:
            - mysql-server 
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            ADMIN_USER: "ADMIN"
            ADMIN_PASSWORD: "ADMIN"